name: 'Hello World'
description: 'Scan Image'
inputs:
  tags:  # id of input
    description: 'Who to greet'
    required: true
    default: ''
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - id: download-lw-scanner
      run: |
        curl -sSL https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner
        chmod +x lw-scanner
      shell: bash
    - run: ./scan.sh ${{ inputs.tags }}
      shell: bash
    - uses: actions/upload-artifact@v3
      with:
        name: lacework-scan-results
        path: lw-scan-result.*
    - uses: actions/github-script@v6
      with:
        script: |
          //const core = require('@actions/core');
          //const github = require('@actions/github');
          //console.log(context);
          const policy = require('./policy.js');
          let message = policy.result(github);
          
          await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
          })
