name: 'Hello World'
description: 'Scan Image'
inputs:
  tags:  # id of input
    description: 'Who to greet'
    required: true
    default: ''
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps:
    - id: download-lw-scanner
      run: |
        curl -sSL https://github.com/lacework/lacework-vulnerability-scanner/releases/latest/download/lw-scanner-linux-amd64 -o lw-scanner
        chmod +x lw-scanner
      shell: bash
    - run: ./scan.sh ${{ inputs.tags }}
      shell: bash
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(context);
          const token = core.getInput('github-token', {required: true});
          const github = new GitHub(token, {} );
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({ issue_number, owner, repo, body: 'Hello world ! 👋' });
