#Sample workflow
name: Build and Scan

on:
  pull_request:
    

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    env:
      LW_ACCESS_TOKEN: ${{ secrets.LW_ACCESS_TOKEN }}
      LW_ACCOUNT_NAME: ${{ secrets.LW_ACCOUNT_NAME }}
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
 
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ env.IMAGE_NAME }}/test-image

    - name: Build and Tag Image
      id: build
      run: docker build -t ${{ steps.meta.outputs.tags }} .

    - name: Lacework Scanner
      id: lacework
      uses: ./
      with:
        tags: ${{ steps.meta.outputs.tags }}